/usr/share/arduino/arduino-builder \
    -dump-prefs -logger=machine \
    -hardware /usr/share/arduino/hardware \
    -hardware /home/annad/.arduino15/packages \
    -tools /usr/share/arduino/tools-builder \
    -tools /home/annad/.arduino15/packages \
    -libraries /home/annad/Arduino/libraries \
    -fqbn=arduino:avr:uno -ide-version=10819 \
    -build-path /tmp/arduino_build_229750 \
    -warnings=none -build-cache /tmp/arduino_cache_211552 \
    -prefs=build.warn_data_percentage=75 \
    -prefs=runtime.tools.avr-gcc.path=/home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7 \
    -prefs=runtime.tools.avr-gcc-7.3.0-atmel3.6.1-arduino7.path=/home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7 \
    -prefs=runtime.tools.avrdude.path=/home/annad/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino17 \
    -prefs=runtime.tools.avrdude-6.3.0-arduino17.path=/home/annad/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino17 \
    -prefs=runtime.tools.arduinoOTA.path=/home/annad/.arduino15/packages/arduino/tools/arduinoOTA/1.3.0 \
    -prefs=runtime.tools.arduinoOTA-1.3.0.path=/home/annad/.arduino15/packages/arduino/tools/arduinoOTA/1.3.0 \
    -verbose /home/annad/Arduino/labvbackend/labvbackend.ino

/usr/share/arduino/arduino-builder \
    -compile -logger=machine \
    -hardware /usr/share/arduino/hardware \
    -hardware /home/annad/.arduino15/packages \
    -tools /usr/share/arduino/tools-builder \
    -tools /home/annad/.arduino15/packages \
    -libraries /home/annad/Arduino/libraries \
    -fqbn=arduino:avr:uno -ide-version=10819 \
    -build-path /tmp/arduino_build_229750 -warnings=none \
    -build-cache /tmp/arduino_cache_211552 \
    -prefs=build.warn_data_percentage=75 \
    -prefs=runtime.tools.avr-gcc.path=/home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7 \
    -prefs=runtime.tools.avr-gcc-7.3.0-atmel3.6.1-arduino7.path=/home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7 \
    -prefs=runtime.tools.avrdude.path=/home/annad/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino17 \
    -prefs=runtime.tools.avrdude-6.3.0-arduino17.path=/home/annad/.arduino15/packages/arduino/tools/avrdude/6.3.0-arduino17 \
    -prefs=runtime.tools.arduinoOTA.path=/home/annad/.arduino15/packages/arduino/tools/arduinoOTA/1.3.0 \
    -prefs=runtime.tools.arduinoOTA-1.3.0.path=/home/annad/.arduino15/packages/arduino/tools/arduinoOTA/1.3.0 \
    -verbose /home/annad/Arduino/labvbackend/labvbackend.ino

# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard -I/home/annad/Arduino/libraries/Adafruit_INA219 -I/home/annad/Arduino/libraries/Adafruit_BusIO -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/SPI/src /tmp/arduino_build_229750/sketch/labvbackend.ino.cpp -o /dev/null
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard -I/home/annad/Arduino/libraries/Adafruit_INA219 -I/home/annad/Arduino/libraries/Adafruit_BusIO -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/SPI/src /tmp/arduino_build_229750/sketch/monochr.cpp -o /dev/null
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard -I/home/annad/Arduino/libraries/Adafruit_INA219 -I/home/annad/Arduino/libraries/Adafruit_BusIO -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/SPI/src /home/annad/Arduino/libraries/Adafruit_INA219/Adafruit_INA219.cpp -o /dev/null
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard -I/home/annad/Arduino/libraries/Adafruit_INA219 -I/home/annad/Arduino/libraries/Adafruit_BusIO -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/SPI/src /home/annad/Arduino/libraries/Adafruit_BusIO/Adafruit_BusIO_Register.cpp -o /dev/null
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard -I/home/annad/Arduino/libraries/Adafruit_INA219 -I/home/annad/Arduino/libraries/Adafruit_BusIO -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/SPI/src /home/annad/Arduino/libraries/Adafruit_BusIO/Adafruit_I2CDevice.cpp -o /dev/null
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard -I/home/annad/Arduino/libraries/Adafruit_INA219 -I/home/annad/Arduino/libraries/Adafruit_BusIO -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/SPI/src /home/annad/Arduino/libraries/Adafruit_BusIO/Adafruit_SPIDevice.cpp -o /dev/null
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard -I/home/annad/Arduino/libraries/Adafruit_INA219 -I/home/annad/Arduino/libraries/Adafruit_BusIO -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/SPI/src /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src/Wire.cpp -o /dev/null
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard -I/home/annad/Arduino/libraries/Adafruit_INA219 -I/home/annad/Arduino/libraries/Adafruit_BusIO -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/SPI/src /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src/utility/twi.c -o /dev/null
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard -I/home/annad/Arduino/libraries/Adafruit_INA219 -I/home/annad/Arduino/libraries/Adafruit_BusIO -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/SPI/src /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/SPI/src/SPI.cpp -o /dev/null
# Generating function prototypes...
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard -I/home/annad/Arduino/libraries/Adafruit_INA219 -I/home/annad/Arduino/libraries/Adafruit_BusIO -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/SPI/src /tmp/arduino_build_229750/sketch/labvbackend.ino.cpp -o /tmp/arduino_build_229750/preproc/ctags_target_for_gcc_minus_e.cpp
# /usr/bin/arduino-ctags -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives /tmp/arduino_build_229750/preproc/ctags_target_for_gcc_minus_e.cpp
# Compiling sketch...
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard -I/home/annad/Arduino/libraries/Adafruit_INA219 -I/home/annad/Arduino/libraries/Adafruit_BusIO -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/SPI/src /tmp/arduino_build_229750/sketch/labvbackend.ino.cpp -o /tmp/arduino_build_229750/sketch/labvbackend.ino.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard -I/home/annad/Arduino/libraries/Adafruit_INA219 -I/home/annad/Arduino/libraries/Adafruit_BusIO -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/SPI/src /tmp/arduino_build_229750/sketch/monochr.cpp -o /tmp/arduino_build_229750/sketch/monochr.cpp.o
# Compiling libraries...
# Compiling library "Adafruit_INA219"
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard -I/home/annad/Arduino/libraries/Adafruit_INA219 -I/home/annad/Arduino/libraries/Adafruit_BusIO -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/SPI/src /home/annad/Arduino/libraries/Adafruit_INA219/Adafruit_INA219.cpp -o /tmp/arduino_build_229750/libraries/Adafruit_INA219/Adafruit_INA219.cpp.o
# Compiling library "Adafruit_BusIO"
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard -I/home/annad/Arduino/libraries/Adafruit_INA219 -I/home/annad/Arduino/libraries/Adafruit_BusIO -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/SPI/src /home/annad/Arduino/libraries/Adafruit_BusIO/Adafruit_BusIO_Register.cpp -o /tmp/arduino_build_229750/libraries/Adafruit_BusIO/Adafruit_BusIO_Register.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard -I/home/annad/Arduino/libraries/Adafruit_INA219 -I/home/annad/Arduino/libraries/Adafruit_BusIO -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/SPI/src /home/annad/Arduino/libraries/Adafruit_BusIO/Adafruit_I2CDevice.cpp -o /tmp/arduino_build_229750/libraries/Adafruit_BusIO/Adafruit_I2CDevice.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard -I/home/annad/Arduino/libraries/Adafruit_INA219 -I/home/annad/Arduino/libraries/Adafruit_BusIO -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/SPI/src /home/annad/Arduino/libraries/Adafruit_BusIO/Adafruit_SPIDevice.cpp -o /tmp/arduino_build_229750/libraries/Adafruit_BusIO/Adafruit_SPIDevice.cpp.o
# Compiling library "Wire"
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard -I/home/annad/Arduino/libraries/Adafruit_INA219 -I/home/annad/Arduino/libraries/Adafruit_BusIO -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/SPI/src /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src/Wire.cpp -o /tmp/arduino_build_229750/libraries/Wire/Wire.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard -I/home/annad/Arduino/libraries/Adafruit_INA219 -I/home/annad/Arduino/libraries/Adafruit_BusIO -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/SPI/src /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src/utility/twi.c -o /tmp/arduino_build_229750/libraries/Wire/utility/twi.c.o
# Compiling library "SPI"
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard -I/home/annad/Arduino/libraries/Adafruit_INA219 -I/home/annad/Arduino/libraries/Adafruit_BusIO -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire/src -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/SPI/src /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/SPI/src/SPI.cpp -o /tmp/arduino_build_229750/libraries/SPI/SPI.cpp.o
# Compiling core...
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc -c -g -x assembler-with-cpp -flto -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/wiring_pulse.S -o /tmp/arduino_build_229750/core/wiring_pulse.S.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/WInterrupts.c -o /tmp/arduino_build_229750/core/WInterrupts.c.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/wiring_analog.c -o /tmp/arduino_build_229750/core/wiring_analog.c.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/hooks.c -o /tmp/arduino_build_229750/core/hooks.c.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/wiring.c -o /tmp/arduino_build_229750/core/wiring.c.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/wiring_digital.c -o /tmp/arduino_build_229750/core/wiring_digital.c.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/wiring_pulse.c -o /tmp/arduino_build_229750/core/wiring_pulse.c.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/wiring_shift.c -o /tmp/arduino_build_229750/core/wiring_shift.c.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/CDC.cpp -o /tmp/arduino_build_229750/core/CDC.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/HardwareSerial1.cpp -o /tmp/arduino_build_229750/core/HardwareSerial1.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/HardwareSerial.cpp -o /tmp/arduino_build_229750/core/HardwareSerial.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/HardwareSerial0.cpp -o /tmp/arduino_build_229750/core/HardwareSerial0.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/HardwareSerial2.cpp -o /tmp/arduino_build_229750/core/HardwareSerial2.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/HardwareSerial3.cpp -o /tmp/arduino_build_229750/core/HardwareSerial3.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/IPAddress.cpp -o /tmp/arduino_build_229750/core/IPAddress.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/PluggableUSB.cpp -o /tmp/arduino_build_229750/core/PluggableUSB.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/Print.cpp -o /tmp/arduino_build_229750/core/Print.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/Stream.cpp -o /tmp/arduino_build_229750/core/Stream.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/Tone.cpp -o /tmp/arduino_build_229750/core/Tone.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/USBCore.cpp -o /tmp/arduino_build_229750/core/USBCore.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/WMath.cpp -o /tmp/arduino_build_229750/core/WMath.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/WString.cpp -o /tmp/arduino_build_229750/core/WString.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/abi.cpp -o /tmp/arduino_build_229750/core/abi.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/main.cpp -o /tmp/arduino_build_229750/core/main.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino -I/home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/variants/standard /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/cores/arduino/new.cpp -o /tmp/arduino_build_229750/core/new.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc-ar rcs /tmp/arduino_build_229750/core/core.a /tmp/arduino_build_229750/core/wiring_pulse.S.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc-ar rcs /tmp/arduino_build_229750/core/core.a /tmp/arduino_build_229750/core/WInterrupts.c.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc-ar rcs /tmp/arduino_build_229750/core/core.a /tmp/arduino_build_229750/core/hooks.c.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc-ar rcs /tmp/arduino_build_229750/core/core.a /tmp/arduino_build_229750/core/wiring.c.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc-ar rcs /tmp/arduino_build_229750/core/core.a /tmp/arduino_build_229750/core/wiring_analog.c.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc-ar rcs /tmp/arduino_build_229750/core/core.a /tmp/arduino_build_229750/core/wiring_digital.c.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc-ar rcs /tmp/arduino_build_229750/core/core.a /tmp/arduino_build_229750/core/wiring_pulse.c.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc-ar rcs /tmp/arduino_build_229750/core/core.a /tmp/arduino_build_229750/core/wiring_shift.c.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc-ar rcs /tmp/arduino_build_229750/core/core.a /tmp/arduino_build_229750/core/CDC.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc-ar rcs /tmp/arduino_build_229750/core/core.a /tmp/arduino_build_229750/core/HardwareSerial.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc-ar rcs /tmp/arduino_build_229750/core/core.a /tmp/arduino_build_229750/core/HardwareSerial0.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc-ar rcs /tmp/arduino_build_229750/core/core.a /tmp/arduino_build_229750/core/HardwareSerial1.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc-ar rcs /tmp/arduino_build_229750/core/core.a /tmp/arduino_build_229750/core/HardwareSerial2.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc-ar rcs /tmp/arduino_build_229750/core/core.a /tmp/arduino_build_229750/core/HardwareSerial3.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc-ar rcs /tmp/arduino_build_229750/core/core.a /tmp/arduino_build_229750/core/IPAddress.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc-ar rcs /tmp/arduino_build_229750/core/core.a /tmp/arduino_build_229750/core/PluggableUSB.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc-ar rcs /tmp/arduino_build_229750/core/core.a /tmp/arduino_build_229750/core/Print.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc-ar rcs /tmp/arduino_build_229750/core/core.a /tmp/arduino_build_229750/core/Stream.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc-ar rcs /tmp/arduino_build_229750/core/core.a /tmp/arduino_build_229750/core/Tone.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc-ar rcs /tmp/arduino_build_229750/core/core.a /tmp/arduino_build_229750/core/USBCore.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc-ar rcs /tmp/arduino_build_229750/core/core.a /tmp/arduino_build_229750/core/WMath.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc-ar rcs /tmp/arduino_build_229750/core/core.a /tmp/arduino_build_229750/core/WString.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc-ar rcs /tmp/arduino_build_229750/core/core.a /tmp/arduino_build_229750/core/abi.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc-ar rcs /tmp/arduino_build_229750/core/core.a /tmp/arduino_build_229750/core/main.cpp.o
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc-ar rcs /tmp/arduino_build_229750/core/core.a /tmp/arduino_build_229750/core/new.cpp.o
# Archiving built core (caching) in: /tmp/arduino_cache_211552/core/core_arduino_avr_uno_02874f02e14134a6d30699d182e119b4.a
# Linking everything together...
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-gcc -w -Os -g -flto -fuse-linker-plugin -Wl,--gc-sections -mmcu=atmega328p -o /tmp/arduino_build_229750/labvbackend.ino.elf /tmp/arduino_build_229750/sketch/labvbackend.ino.cpp.o /tmp/arduino_build_229750/sketch/monochr.cpp.o /tmp/arduino_build_229750/libraries/Adafruit_INA219/Adafruit_INA219.cpp.o /tmp/arduino_build_229750/libraries/Adafruit_BusIO/Adafruit_BusIO_Register.cpp.o /tmp/arduino_build_229750/libraries/Adafruit_BusIO/Adafruit_I2CDevice.cpp.o /tmp/arduino_build_229750/libraries/Adafruit_BusIO/Adafruit_SPIDevice.cpp.o /tmp/arduino_build_229750/libraries/Wire/Wire.cpp.o /tmp/arduino_build_229750/libraries/Wire/utility/twi.c.o /tmp/arduino_build_229750/libraries/SPI/SPI.cpp.o /tmp/arduino_build_229750/core/core.a -L/tmp/arduino_build_229750 -lm
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-objcopy -O ihex -j .eeprom --set-section-flags=.eeprom=alloc,load --no-change-warnings --change-section-lma .eeprom=0 /tmp/arduino_build_229750/labvbackend.ino.elf /tmp/arduino_build_229750/labvbackend.ino.eep
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-objcopy -O ihex -R .eeprom /tmp/arduino_build_229750/labvbackend.ino.elf /tmp/arduino_build_229750/labvbackend.ino.hex
# Using library Adafruit_INA219 at version 1.2.1 in folder: /home/annad/Arduino/libraries/Adafruit_INA219 
# Using library Adafruit_BusIO at version 1.14.3 in folder: /home/annad/Arduino/libraries/Adafruit_BusIO 
# Using library Wire at version 1.0 in folder: /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/Wire 
# Using library SPI at version 1.0 in folder: /home/annad/.arduino15/packages/arduino/hardware/avr/1.8.6/libraries/SPI 
# /home/annad/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/bin/avr-size -A /tmp/arduino_build_229750/labvbackend.ino.elf
# Sketch uses 6830 bytes (21%) of program storage space. Maximum is 32256 bytes.
