name: arduino_ci
run-name: ${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "Checkout: ${{ github.repository }}."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "Status: ${{ job.status }}."
