name: arduino_ci
run-name: ${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - name: Check out repository code
        uses: actions/checkout@master
      - run: echo "Checkout ${{ github.repository }}."
        
      - name: Instaling arduino...
        run: |
          sudo apt install arduino
      
      - name: Compiling...
        run: |
          /usr/share/arduino/arduino-builder --help
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - run: echo "Status ${{ job.status }}."
      
