name: arduino_ci
run-name: ${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "Checkout ${{ github.repository }}."
      
      - name: Install dependencies
      # flex byacc bison uisp
        run: |
          mkdir arduino |
          cd arduino |
          wget https://downloads.arduino.cc/arduino-1.8.15-linux64.tar.xz |
          tar -xvf ./arduino-1.8.15-linux64.tar.xz |
          cd arduino-1.8.15 | 
          sudo chmod +x ./install.sh |
          sudo ./install.sh
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - run: echo "Status ${{ job.status }}."
      
