name: arduino_ci
run-name: ${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - name: Check out repository code
        uses: actions/checkout@master
      - run: echo "Checkout ${{ github.repository }}."
      
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      
      - name: Compile
        run: |
          arduino-cli --help
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - run: echo "Status ${{ job.status }}."
      
