name: CI
run-name: ${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Install dependencies
      - run: apt-get install avrdude
      
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "Status: ${{ job.status }}."
