on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - name: Check out repository code
        uses: actions/checkout@master

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Platform
        run: arduino-cli core install arduino:avr

      - name: Install dependencies
        run: arduino-cli lib install "Adafruit ADS1X15@2.4.0"
      
      - name: Compile
        run: ./build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: debug
          path: ./debug

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Calculate Short SHA.
        id: vars
        run: echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: debug

      - name: Archive artifacts
        uses: thedoctor0/zip-release@master
        with:
          filename: debug.zip

      - name: Create GitHub Release
        id: create-release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ secrets.GITHUB_SHA }}
          release_name: Release ${{ secrets.GITHUB_SHA }} 
