on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - name: Check out repository code
        uses: actions/checkout@master
      
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Platform
        run: arduino-cli core install arduino:avr

      - name: Install dependencies
        run: arduino-cli lib install "Adafruit ADS1X15@2.4.0"
      
      - name: Compile
        run: ./build.sh
      
