name: arduino_ci
run-name: ${{ github.actor }}
on: [push]
jobs:
  build:
    strategy:
      matrix:
        arduino-platform: ["arduino:avr"]
        include:
          - arduino-platform: "arduino:avr"
            fqbn: "arduino:avr:uno"
    runs-on: ubuntu-latest
    steps:    
      - name: Check out repository code
        uses: actions/checkout@master
      - run: echo "Checkout ${{ github.repository }}."

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1
        
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install $

      - name: Compile Sketch
        run: arduino-cli compile --fqbn $ labvbackend --warnings more 
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - run: echo "Status ${{ job.status }}."
      
